### ISSUE TITLE
ImportError: cannot import name region

### ISSUE THREAD

**Issue by chenbolinstudent** [STVIR/pysot#28] opened 2019-06-04 08:22 UTC
ImportError: cannot import name region @

**Comment by lb1100** [comment] 2019-06-04 08:51
Duplicate of #16. Please refer to [INSTALL.md](https://github.com/STVIR/pysot/blob/master/INSTALL.md)

**Closed by lb1100** 2019-06-04 08:51 UTC

**Comment by chenbolinstudent** [comment] 2019-06-04 11:49
thanks,when it offer the training code?
@lb1100
