### ISSUE TITLE
libtorch如何加载pysot训练的.pth模型文件？

### ISSUE THREAD

**Issue by itfish** [STVIR/pysot#150] opened 2019-08-06 01:41 UTC

**Comment by lb1100** [comment] 2019-08-06 03:09
Duplicate of #146. Please watch this issue. If the problem solved, we'll update here.

**Closed by lb1100** 2019-08-06 03:09 UTC

**Comment by itfish** [comment] 2019-08-06 05:37
my problem is not solved. could you give me the solution about how to use pysot's .pth model with c++ language?

**Comment by lb1100** [comment] 2019-08-06 06:33
Sorry, what I meant is we will update this on #146. These two issues are duplicated.

**Comment by itfish** [comment] 2019-08-06 09:48
ok,can you help me to solve this problem?

**Comment by mqingkui** [comment] 2019-10-15 08:40
@itfish have you solved pth->pt problem？
