### ISSUE TITLE
ValueError: could not convert string to float: 'Occ'

### ISSUE THREAD

**Issue by smile-fyl** [STVIR/pysot#232] opened 2019-11-11 08:35 UTC
When I run the project of 'eval.py' ,there has question as follow:

Traceback (most recent call last):
  File "/home/omnisky/anaconda3/envs/pysot/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/mnt/omnisky/personal/fu/pysot/toolkit/evaluation/ar_benchmark.py", line 37, in eval
    accuracy, failures = self._calculate_accuracy_robustness(tracker_name)
  File "/mnt/omnisky/personal/fu/pysot/toolkit/evaluation/ar_benchmark.py", line 126, in _calculate_accuracy_robustness
    tracker_trajs = video.load_tracker(self.dataset.tracker_path, tracker_name, False)
  File "/mnt/omnisky/personal/fu/pysot/toolkit/datasets/vot.py", line 84, in load_tracker
    for x in f.readlines()]
  File "/mnt/omnisky/personal/fu/pysot/toolkit/datasets/vot.py", line 84, in <listcomp>
    for x in f.readlines()]
ValueError: could not convert string to float: 'Occ'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "../../tools/eval.py", line 146, in <module>
    main()
  File "../../tools/eval.py", line 121, in main
    trackers), desc='eval ar', total=len(trackers), ncols=100):
  File "/home/omnisky/anaconda3/envs/pysot/lib/python3.7/site-packages/tqdm/_tqdm.py", line 1017, in __iter__
    for obj in iterable:
  File "/home/omnisky/anaconda3/envs/pysot/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
ValueError: could not convert string to float: 'Occ'

**Comment by Cassiel829** [comment] 2020-05-08 12:39
@smile-fyl Hi, I met the same problem,did you solve it?THX

**Comment by zyc-ai** [comment] 2020-07-21 02:00
Sorry for this late reply, can you please provide detailed steps to reproduce this issue?

**Comment by zyc-ai** [comment] 2020-09-07 13:28
Since no further question is asked, I'm closing this issue for now. 
Please create a new issue should you have other questions.

**Closed by zyc-ai** 2020-09-07 13:28 UTC
Labels: question
