### ISSUE TITLE
Train epoch=20,but in the snapshot : only have e1-e19

### ISSUE THREAD

**Issue by smile-fyl** [STVIR/pysot#188] opened 2019-09-24 13:50 UTC
When I was training this project  two weeks ago,in the snapshot folder,here will generate 20 files(e1-e20).But now,I find in this folder only have 19 files(e1-e19).Both train epoch are the same(train epoch=20).But I don't know why？Thanks for your reply.

**Comment by yc-zc** [comment] 2019-12-27 09:30
Please provide steps to reproduce.

**Comment by yc-zc** [comment] 2020-01-08 14:59
Since no further question is asked, I'm closing it for now.
Please reopen it or create a new issue if you have further question.

**Closed by yc-zc** 2020-01-08 14:59 UTC
Labels: question
