### ISSUE TITLE
训练的问题

### ISSUE THREAD

**Issue by chenbolinstudent** [STVIR/pysot#135] opened 2019-07-29 09:03 UTC
1.为什么8块和16块的GPU在训练的参数不同？
2.为什么针对不同测试数据集，训练的参数不同？
谢谢回复。

**Comment by lb1100** [comment] 2019-07-29 10:38
Due to the huge number of random operations in training, (e.g. random frame of random track of random video. We can guarantee that each video is sampled at least once, however, we can't guarantee every frames are sampled.), training results are not stable. If using different cards during training, data fed into network will not be the same. So some hyper-parameters need to change. However we haven't found a way to stabilize training, it needs to be tested what is the best training parameters.
  However, you can use `hp_search.py` to search hyper parameters during testing. That will help too. 
  About different datasets, the reasons are mainly the same. It mainly caused by random. However, if you ask about OTB, there is anchor reason that OTB contains gray videos. Therefore we add some gray augmentation during training just like SiamFC.

**Comment by chenbolinstudent** [comment] 2019-07-29 10:44
thanks, but how to use hp_search.py to search hyper parameters during testing ?
could you give the detail or example?

**Comment by lb1100** [comment] 2019-07-29 10:50
```bash
python $root/tools/hy_search.py --snapshot snapshot/checkpoint_e15.pth \
    --dataset VOT2018 \
    --config config.yaml \
    ----penalty-k ...
```
Use this to search, then evaluate with `eval.py`.

**Comment by chenbolinstudent** [comment] 2019-07-29 11:01
thanks,
when only have 2 GPU，use the parameters of 8 GPU or 16 GPU will get the better result?
and the model will test all the test dataset?

**Comment by chenbolinstudent** [comment] 2019-07-29 11:02
thanks,
when only have 2 GPU，use the parameters of 8 GPU or 16 GPU will get the better result?
and the model will test all the test dataset?
and the batch=16 will better than the 26?(cannot set to 28)

**Comment by beihaifusang** [comment] 2019-10-16 09:00
> thanks,
> when only have 2 GPU，use the parameters of 8 GPU or 16 GPU will get the better result?
> and the model will test all the test dataset?
> and the batch=16 will better than the 26?(cannot set to 28)

May I ask if you get any empirical result by this time, regarding which parameter setting would be better?

**Comment by yc-zc** [comment] 2019-12-18 15:44
> thanks,
> when only have 2 GPU，use the parameters of 8 GPU or 16 GPU will get the better result?
> and the model will test all the test dataset?
> and the batch=16 will better than the 26?(cannot set to 28)

I wouldn't recommend you to use the same parameters as your GPU memory would probably be insufficient.

**Comment by yc-zc** [comment] 2019-12-18 15:44
Since no further question is asked, I'm closing it for now.
Please reopen it or create a new issue if you have further question.

**Closed** 2020-05-12 07:27 UTC
Labels: good first issue
