### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by chenbolinstudent** [STVIR/pysot#257] opened 2019-12-10 09:12 UTC
AttributeError: 'NoneType' object has no attribute 'shape'
 what is the problem?
thanks

**Comment by yc-zc** [comment] 2019-12-10 10:11
Could you provide more details on how to reproduce the Error?

**Comment by xiaqing10** [comment] 2019-12-11 02:54
Maybe the picture is None, you should check input imgs first.

**Comment by yc-zc** [comment] 2019-12-18 16:40
Since no further question is asked, I'm closing it for now.
Please reopen it or create a new issue if you have further question.

**Closed by yc-zc** 2019-12-18 16:40 UTC

**Comment by ThomasBomjan** [comment] 2020-01-07 09:54
I got same issue. Did you manage to solve it ?
