### ISSUE TITLE
I can not download models in PySOT Model Zoo

### ISSUE THREAD

**Issue by ztr1918294** [STVIR/pysot#24] opened 2019-05-31 05:15 UTC
Hi, you said we should download models in PySOT Model Zoo and put the model.pth in the correct directory in experiments
But When I clicked the url link of siamrpn_r50_l234_dwxcorr on https://github.com/STVIR/pysot/blob/master/MODEL_ZOO.md, the web went to https://drive.google.com/open?id=1Q4-1563iPwV6wSf_lBHDj5CPFiGSlEPG which I can not open

**Comment by lb1100** [comment] 2019-05-31 09:13
Duplicate of #5. Try use BaiduYun.

**Closed by lb1100** 2019-05-31 09:13 UTC
